global:
  scrape_interval: 5s # Scrape frequently for real-time monitoring in this assessment

scrape_configs:
  - job_name: "jition-backend"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["backend:3000"]
